Repository AY2021S1-CS2103T-W11-2/tp, pull requests merged in 2020-10, with the labels that each got.

#83 Add task including todos, events and deadlines
  docs/AboutUs.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/TaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/flag/Flag.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Event.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/Todo.java
  src/main/java/seedu/address/model/task/UniqueTasksList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium, severity.Medium

#106 Temp view tasklist
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ViewTaskListCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/flag/Flag.java
Labels: priority.Low

#107 Enable Assertions
  build.gradle
Labels: priority.Low, severity.Low, type.Task

#108 Add Unit tests for ScraperManager class
  debug.log
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/scraper/ScraperManager.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/scraper/ScraperManagerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.Medium, type.Task

#114 Quest related features
  .gitignore
  login.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/mission/Mission.java
  src/main/java/seedu/address/model/quest/Quest.java
  src/main/java/seedu/address/model/student/UniqueStudentsList.java
  src/main/java/seedu/address/scraper/Scraper.java
  src/main/java/seedu/address/scraper/ScraperManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MissionListPanel.java
  src/main/java/seedu/address/ui/QuestCard.java
  src/main/java/seedu/address/ui/QuestListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QuestListCard.fxml
  src/main/resources/view/QuestListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/scraper/ScraperManagerTest.java
Labels: priority.High, severity.High

#135 Add diagram
  docs/DeveloperGuide.md
  docs/diagrams/ViewCommandClassDiagram.puml
  docs/diagrams/ViewMissionDeadlineSequenceDiagram.puml
  docs/images/ViewCommandClassDiagram.png
  docs/images/ViewMissionDeadlineSequenceDiagram.png
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/mission/Mission.java
  src/main/java/seedu/address/model/mission/MissionList.java
  src/main/java/seedu/address/model/student/UniqueStudentsList.java
  src/main/java/seedu/address/scraper/ScraperManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: documentation, priority.Medium, severity.Low

#139 Assertion and documentation
  docs/DeveloperGuide.md
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/tracing/AddCommandClassDiagram.puml
  docs/images/AddTaskSequenceDiagram.PNG
  src/main/java/seedu/address/logic/commands/ViewTaskListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskCommandParser.java
Labels: documentation

#151 Ug
  docs/UserGuide.md
Labels: documentation, priority.Medium, severity.Low

#152 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandClassDiagram.puml
  docs/diagrams/AddTaskClassDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/ScraperClassDiagram.puml
  docs/diagrams/ViewCommandClassDiagram.puml
  docs/diagrams/ViewConsultationsClassDiagram.puml
  docs/diagrams/ViewStudentsClassDiagram.puml
  docs/diagrams/tracing/AddCommandClassDiagram.puml
  docs/images/AddCommandClassDiagram.png
  docs/images/AddTaskClassDiagram.png
  docs/images/AddTaskSequenceDiagram.PNG
  docs/images/AddTaskSequenceDiagram.png
  docs/images/ScraperClassDiagram.png
  docs/images/ViewCommandClassDiagram.png
  docs/images/ViewConsultationsClassDiagram.png
  docs/images/ViewStudentsClassDiagram.png
Labels: documentation

#153 Update UG and DG diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ViewAllStudentsSequenceDiagram.puml
  docs/images/ViewAllStudentsSequenceDiagram.png
Labels: documentation

#157 UGDG touchups
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/ViewConsultationsSequenceDiagram.puml
  docs/images/AddTaskSequenceDiagram.png
  docs/images/ViewConsultationsSequenceDiagram.png
  docs/index.md
Labels: documentation

#158 Add assertions
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/mission/MissionList.java
Labels: priority.Medium, severity.Medium

#161 Load, Delete and View task features added
  .gitignore
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ViewTaskListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/flag/Flag.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Event.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTasksList.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/scraper/ScraperManager.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.Medium, severity.Medium

#169 Add test cases for mission related features
  src/main/java/seedu/address/model/mission/Mission.java
  src/main/java/seedu/address/model/quest/Quest.java
  src/test/java/seedu/address/logic/commands/ViewMissionDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewUngradedMissionCommandTest.java
  src/test/java/seedu/address/model/mission/MissionListTest.java
  src/test/java/seedu/address/model/mission/MissionTest.java
  src/test/java/seedu/address/testutil/MissionBuilder.java
  src/test/java/seedu/address/testutil/TypicalMissions.java
Labels: priority.Medium, severity.Medium, type.Task

#183 Implement tabs in GUI
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/scraper/ScraperManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/jarvis.png
  src/main/resources/images/source_academy.png
  src/main/resources/images/user_guide.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High, severity.High, type.Task

#190 Update UG
  docs/UserGuide.md
  docs/images/userguide/addFormat.PNG
  docs/images/userguide/deleteFormat.PNG
  docs/images/userguide/editFormat.PNG
  docs/images/userguide/exitFormat.PNG
  docs/images/userguide/helpFormat.PNG
  docs/images/userguide/viewFormat.PNG
Labels: documentation, severity.VeryLow

#198 View task gui
  src/main/java/seedu/address/logic/commands/ViewTaskListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
Labels: priority.High, severity.High

#203 Mofidy GUI Formatting
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Medium, type.Enhancement

#210 Personalise GUI with user's name
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/scraper/ScraperManager.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.Medium, severity.Low, type.Enhancement

#230 Change greeting dynamically
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/greeting/Greeting.java
  src/main/java/seedu/address/scraper/ScraperManager.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#233 Add UG header links to table of content
  docs/UserGuide.md
Labels: documentation

#235 Change UG image extensions
  docs/UserGuide.md
  docs/images/userguide/Jarvis.png
  docs/images/userguide/addDeadline.png
  docs/images/userguide/addEvent.png
  docs/images/userguide/addFormat.png
  docs/images/userguide/addTodo.png
  docs/images/userguide/deleteFormat.png
  docs/images/userguide/deleteTask.png
  docs/images/userguide/editFormat.png
  docs/images/userguide/exitFormat.png
  docs/images/userguide/helpFormat.png
  docs/images/userguide/viewAllStudents.png
  docs/images/userguide/viewFormat.png
  docs/images/userguide/viewOneStudent.png
  docs/images/userguide/viewUngradedMissions.png
  docs/images/userguide/viewUngradedQuests.png
Labels: documentation

#236 Ug update wk12
  docs/UserGuide.md
Labels: documentation, priority.Medium

#237 Update command summary
  docs/UserGuide.md
  docs/images/userguide/addFormat.png
  docs/images/userguide/deleteFormat.png
  docs/images/userguide/editFormat.png
  docs/images/userguide/exitFormat.png
  docs/images/userguide/helpFormat.png
  docs/images/userguide/viewFormat.png
Labels: documentation
