Repository AY2021S1-CS2103T-W11-2/tp, pull requests merged in 2020-11, with the labels that each got.

#272 GUI/invalid messages
  docs/UserGuide.md
  src/main/java/seedu/jarvis/logic/commands/FindCommand.java
  src/main/java/seedu/jarvis/logic/commands/edit/EditCommand.java
  src/main/java/seedu/jarvis/logic/parser/AddCommandParser.java
  src/main/java/seedu/jarvis/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/jarvis/logic/parser/EditCommandParser.java
  src/main/java/seedu/jarvis/logic/parser/ViewCommandParser.java
  src/main/java/seedu/jarvis/model/UserPrefs.java
  src/main/java/seedu/jarvis/model/topic/Topic.java
  src/main/java/seedu/jarvis/model/util/SampleDataUtil.java
  src/main/java/seedu/jarvis/ui/HelpWindow.java
  src/main/java/seedu/jarvis/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/jarvis/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/jarvis/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/jarvis/model/quest/QuestTest.java
  src/test/java/seedu/jarvis/testutil/QuestBuilder.java
  src/test/java/seedu/jarvis/testutil/TypicalQuests.java
  typicalPersonsAddressBook.json
Labels: priority.Medium, severity.Low, type.Task

#275 Update color for selected tab
  src/main/resources/view/DarkTheme.css
Labels: priority.Medium, severity.Low, type.Task

#280 Fix dryrun PE Task related bugs
  docs/UserGuide.md
  src/main/java/seedu/jarvis/logic/commands/add/AddCommand.java
  src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java
Labels: documentation, priority.High, severity.High, type.Bug

#283 Update Wiline's PPP
  docs/AboutUs.md
  docs/team/wilinetan.md
  src/main/java/seedu/jarvis/ui/MainWindow.java
Labels: documentation

#296 update jj ppp
  docs/team/asuraxsoul.md
Labels: documentation

#297 Update UG
  docs/UserGuide.md
Labels: documentation

#298 Add UP and DOWN key presses to access command history in CommandBox
  src/main/java/seedu/jarvis/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: priority.Medium, severity.Medium, type.Enhancement

#299 Add & Delete command Abstractions
  docs/UserGuide.md
  docs/team/asuraxsoul.md
  docs/team/peironggg.md
  docs/team/wilinetan.md
  src/main/java/seedu/jarvis/logic/commands/add/AddCommand.java
  src/main/java/seedu/jarvis/logic/commands/add/AddConsultationCommand.java
  src/main/java/seedu/jarvis/logic/commands/add/AddMasteryCheckCommand.java
  src/main/java/seedu/jarvis/logic/commands/add/AddTaskCommand.java
  src/main/java/seedu/jarvis/logic/commands/delete/DeleteCommand.java
  src/main/java/seedu/jarvis/logic/commands/delete/DeleteConsultationCommand.java
  src/main/java/seedu/jarvis/logic/commands/delete/DeleteMasteryCheckCommand.java
  src/main/java/seedu/jarvis/logic/commands/delete/DeleteTaskCommand.java
  src/main/java/seedu/jarvis/logic/parser/AddCommandParser.java
  src/main/java/seedu/jarvis/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/jarvis/model/task/Task.java
  src/test/java/seedu/jarvis/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/jarvis/logic/commands/AddCommandTest.java
Labels: priority.Low, severity.VeryLow, type.Task

#303 Add tests for quests, topics and greeting
  src/main/java/seedu/jarvis/model/quest/QuestList.java
  src/main/java/seedu/jarvis/model/topic/Topic.java
  src/test/java/seedu/jarvis/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/jarvis/model/greeting/GreetingTest.java
  src/test/java/seedu/jarvis/model/quest/QuestListTest.java
  src/test/java/seedu/jarvis/model/topic/TopicTest.java
  src/test/java/seedu/jarvis/model/topic/TopicsTest.java
  src/test/java/seedu/jarvis/testutil/TypicalQuests.java
Labels: priority.Medium, severity.Low, type.Task

#310 Update task unit test
  docs/team/asuraxsoul.md
  src/main/java/seedu/jarvis/logic/commands/add/AddConsultationCommand.java
  src/main/java/seedu/jarvis/logic/commands/add/AddMasteryCheckCommand.java
  src/main/java/seedu/jarvis/model/task/Deadline.java
  src/main/java/seedu/jarvis/model/task/Event.java
  src/main/java/seedu/jarvis/model/task/Task.java
  src/main/java/seedu/jarvis/model/task/Todo.java
  src/main/java/seedu/jarvis/model/task/UniqueTasksList.java
  src/test/java/seedu/jarvis/model/task/DeadlineTest.java
  src/test/java/seedu/jarvis/model/task/EventTest.java
  src/test/java/seedu/jarvis/model/task/TaskTest.java
  src/test/java/seedu/jarvis/model/task/TodoTest.java
  src/test/java/seedu/jarvis/model/task/UniqueTasksListTest.java
Labels: priority.Medium, severity.Low, type.Task

#316 Ug discrepancies update
  docs/UserGuide.md
  src/main/java/seedu/jarvis/model/task/Task.java
Labels: documentation

#347 Add unit tests for Task related Classes
  src/main/java/seedu/jarvis/model/Model.java
  src/main/java/seedu/jarvis/model/ModelManager.java
  src/test/java/seedu/jarvis/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/jarvis/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/jarvis/logic/commands/ViewTaskListCommandTest.java
  src/test/java/seedu/jarvis/model/task/DeadlineTest.java
  src/test/java/seedu/jarvis/model/task/EventTest.java
  src/test/java/seedu/jarvis/model/task/TodoTest.java
  src/test/java/seedu/jarvis/model/task/UniqueTasksListTest.java
  src/test/java/seedu/jarvis/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/jarvis/testutil/DeadlineBuilder.java
  src/test/java/seedu/jarvis/testutil/EventBuilder.java
  src/test/java/seedu/jarvis/testutil/ModelStub.java
  src/test/java/seedu/jarvis/testutil/TodoBuilder.java
  src/test/java/seedu/jarvis/testutil/TypicalStudents.java
  src/test/java/seedu/jarvis/testutil/TypicalTasks.java
Labels: priority.Medium, severity.Low, type.Task

#353 Update DG and other documentations
  README.md
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/ViewCommandClassDiagram.puml
  docs/diagrams/ViewCommandParserClassDiagram.puml
  docs/diagrams/ViewMissionDeadlinePathDiagram.puml
  docs/images/ViewCommandClassDiagram.png
  docs/images/ViewCommandParserClassDiagram.png
  docs/images/ViewMissionDeadlinePathDiagram.png
  docs/index.md
  src/main/java/seedu/jarvis/commons/core/LogsCenter.java
Labels: documentation

#355 Add tests for task addcommandparser and viewcommandparser
  src/test/java/seedu/jarvis/logic/commands/CommandTestUtil.java
  src/test/java/seedu/jarvis/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/jarvis/logic/parser/ViewCommandParserTest.java
Labels: priority.Medium

#361 Update UG content page, DG links and view mission screenshots in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/userguide/viewMissionDeadline.png
  docs/images/userguide/viewUngradedMission.png
  src/main/java/seedu/jarvis/scraper/ScraperManager.java
Labels: documentation

#365 Update viewMissiondDeadline screenshot
  docs/images/userguide/viewMissionDeadline.png
Labels: documentation

#364 Add Command Dg diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandClassDiagram.puml
  docs/diagrams/AddCommandParserClassDiagram.puml
  docs/diagrams/AddCommandPathDiagram.puml
  docs/diagrams/AddTaskClassDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/AddXYZCommandClassDiagram.puml
  docs/images/AddCommandClassDiagram.png
  docs/images/AddCommandParserClassDiagram.png
  docs/images/AddCommandPathDiagram.png
  docs/images/AddTaskClassDiagram.png
  docs/images/AddTaskSequenceDiagram.png
  docs/images/AddXYZCommandClassDiagram.png
  src/main/java/seedu/jarvis/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java
Labels: documentation

#371 Ug update2
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandClassDiagram.puml
  docs/diagrams/AddCommandParserClassDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/AddXYZCommandClassDiagram.puml
  docs/images/AddCommandClassDiagram.png
  docs/images/AddCommandParserClassDiagram.png
  docs/images/AddTaskSequenceDiagram.png
  docs/images/AddXYZCommandClassDiagram.png
Labels: documentation, priority.Medium

#370 Update view command
  docs/DeveloperGuide.md
  docs/diagrams/ViewCommandClassDiagram.puml
  docs/diagrams/ViewMissionDeadlinePathDiagram.puml
  docs/diagrams/ViewMissionDeadlineSequenceDiagram.puml
  docs/images/ViewCommandClassDiagram.png
  docs/images/ViewMissionDeadlinePathDiagram.png
  docs/images/ViewMissionDeadlineSequenceDiagram.png
Labels: documentation

#377 Debug UG
  docs/UserGuide.md
  docs/images/userguide/addConsultation.png
  docs/images/userguide/addMasteryCheck.png
  docs/images/userguide/deleteConsultation.png
  docs/images/userguide/deleteMasteryCheck.png
  docs/images/userguide/deleteTask.png
  docs/images/userguide/editMasteryCheck.png
  docs/images/userguide/viewAllStudents.png
  docs/images/userguide/viewOneStudent.png
  docs/images/userguidess/Jarvis.png
  docs/images/userguidess/addConsultation.png
  docs/images/userguidess/addDeadline.png
  docs/images/userguidess/addEvent.png
  docs/images/userguidess/addMasteryCheck.png
  docs/images/userguidess/addTodo.png
  docs/images/userguidess/deleteTask.png
  docs/images/userguidess/editLoginDetails.png
  docs/images/userguidess/loginPrompt.png
  docs/images/userguidess/viewAllStudents.png
  docs/images/userguidess/viewMissions.png
  docs/images/userguidess/viewOneStudent.png
  docs/images/userguidess/viewQuests.png
  docs/images/userguidess/viewUngradedMissions.png
  docs/images/userguidess/viewUngradedQuests.png
Labels: documentation

#380 Update dg addcommandclass diag, add some task tests
  docs/diagrams/AddCommandClassDiagram.puml
  docs/images/AddCommandClassDiagram.png
  src/main/java/seedu/jarvis/logic/commands/add/AddTaskCommand.java
  src/test/java/seedu/jarvis/logic/parser/AddCommandParserTest.java
Labels: documentation

#378 Add content page and fix diagrams in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandClassDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/DeleteConsultationSequenceDiagram.puml
  docs/diagrams/EditLoginCommandSequenceDiagram.puml
  docs/diagrams/LoginPathDiagram.puml
  docs/diagrams/ViewAllStudentsSequenceDiagram.puml
  docs/diagrams/ViewConsultationsClassDiagram.puml
  docs/diagrams/ViewConsultationsSequenceDiagram.puml
  docs/diagrams/ViewMissionDeadlineSequenceDiagram.puml
  docs/diagrams/ViewStudentsClassDiagram.puml
  docs/images/AddCommandClassDiagram.png
  docs/images/AddTaskSequenceDiagram.png
  docs/images/DeleteConsultationSequenceDiagram.png
  docs/images/EditLoginCommandSequenceDiagram.png
  docs/images/LoginPathDiagram.png
  docs/images/ViewAllStudentsSequenceDiagram.png
  docs/images/ViewConsultationsClassDiagram.png
  docs/images/ViewConsultationsSequenceDiagram.png
  docs/images/ViewMissionDeadlineSequenceDiagram.png
  docs/images/ViewStudentsClassDiagram.png
Labels: documentation

#382 Update Wiline's PPP
  docs/team/johndoe.md
  docs/team/wilinetan.md
Labels: documentation

#383 Add unit Tests
  src/main/java/seedu/jarvis/logic/parser/TaskCommandParser.java
  src/main/java/seedu/jarvis/model/task/Deadline.java
  src/main/java/seedu/jarvis/model/task/Event.java
  src/test/java/seedu/jarvis/logic/commands/CommandTestUtil.java
  src/test/java/seedu/jarvis/logic/parser/AddCommandParserTest.java
Labels: priority.Medium, type.Task

#385 Polish error messages
  docs/team/asuraxsoul.md
  src/main/java/seedu/jarvis/commons/core/Messages.java
  src/main/java/seedu/jarvis/logic/commands/add/AddCommand.java
  src/main/java/seedu/jarvis/logic/parser/AddCommandParser.java
  src/test/java/seedu/jarvis/logic/parser/AddCommandParserTest.java
Labels: priority.Medium

#399 Update UG to reflect mac users
  docs/UserGuide.md
  src/main/java/seedu/jarvis/scraper/ScraperManager.java
Labels: documentation
